### ISSUE TITLE
[Discussão] Que linguagem vamos usar?

### ISSUE THREAD

**Issue by matheuspoleza** [OndaDura/od_api#1]
Então, galera, precisamos decidir que linguagem vamos usar. A ideia dessa api é fazer toda parte de backend do sistema RESTFUL, ou seja, ser um webservice que retorna dados em JSON. 

Provavelmente, vamos usar um framework também. Então queria saber a opinião de vocês. Considerem as seguintes coisas:

- Comunidade 
- Facilitadade de programação (Linguagem fácil de utilizar e aprender)
- Escalabilidade (Fácil de dar manutenção futuramente)
- Qualidade da linguagem

**Comment by imarinheiro** [comment]
Eu voto em Python para back-end. Parece chato mas é uma linguagem com alta curva de aprendizado e potencial enorme de mercado.

**Comment by migueljoaod** [comment]
Eu concordo com o Iago, voto em Python..

**Comment by matheuspoleza** [comment]
Eu acho top Python/Django. É muito fácil de aprender e essa aplicação seria feita em 1 semana haha a parte de backend. Mas quero saber mais opiniões pra decidir haha

**Comment by rafaelcneves** [comment]
Sou defensor do ruby, é provavelmente a linguagem mais facil de aprender, e com padrões mais amigáveis e mais bem definidos, existe uma ampla comunidade no exterior e provavelmente a linguagem com mais facil acesso a plugins e código de terceiros, mas como devo ser o unico que conhece, talvez não seja a mais indicada.

Por mais que não conheça python reconheço a visibilidade dela no mercado e isso acrescenta muito na questão aprendizado e na questão que vai ser útil pra galera no mercado de trabalho. E também tenho interesse em aprender.

PHP sou totalmente contra, apesar de ser uma linguagem bastante difundida, a comunidade se tornou uma bagunça, com isso foi pro ralo padrões e manutenção ou adaptações de codigos de terceiro.

Java, nem comento nada, só se estiver atos 20:24 em jogo :yum:

**Comment by matheuspoleza** [comment]
hahaha palmas para o comentário do @rafaelcneves

**Comment by imarinheiro** [comment]
HAHA, {palmas}.
Eu sou contra PHP também, perdão ai para os phpzeiros de plantão. Pelos mesmos motivos do Rafael.

Java eu gosto muito, mas não vejo promissora, e nem se encontra com os objetivos da proposta em partida dos projetos apresentados para a Onda até o momento.

Ruby me deixa curioso a aprender, talvez seja indicada se a maioria a dominar no grupo de desenvolvimento. Portanto deixo claro que não conheço tanto sobre Ruby a ponto de dizer que seria melhor que Python quando se trata de agilidade, compreensão e etc. Entretanto ela entra como segunda opção na minha lista.

**Comment by matheuspoleza** [comment]
É, concordo que Ruby seria uma opção viável. Ouço falar muito bem, já pesquisa sobre ela e parece uma linguagem fácil de aprender, de alta escabilidade, uma comunidade bem ativa e um reconhecimento grande no mercado de fora. Fica como minha segunda opção também, porque tenho desejo de aprender.

**Comment by bielcorrea** [comment]
Sempre fui "phpzeiro", porém fui me decepcionando cada dia mais com a linguagem pelos motivos que vocês já apresentaram... Tenho um desejo enorme de entrar no ramo do Ruby, sempre ouvi falar bem, e parece muito fácil de aprender, meu voto vai para Ruby ;)

Lembrando que a linguagem vai ser escolhida hoje. Caso tenham alguma outra em mente, ja joguem ai.

**Comment by imarinheiro** [comment]
3 Python x 2 Ruby

**Comment by lealleonardo** [comment]
Cara eu piro em Java (não me julguem kkk). Dependendo de como for o conhecimento na linguagem da galera é inviável, pois a curva de aprendizado é um pouco mais abrangente dependendo das ferramentas e recursos a se utilizar. Eu piro pq foi a última que "tive contato" e usaria de boas. As outras mencionadas, apenas conheço PHP, mas estou a bastante tempo "longe dela". 

Decidindo uma linguagem que favoreça a ideia do sistema da onda e a equipe, vamos de cabeça! :)

**Comment by rodrigs07** [comment]
Boa tarde!

Tanto python quanto ruby são altamente viáveis! Apesar de ter conhecimento das duas, talvez python (pela maioria) seja a melhor escolha!

**Comment by bielcorrea** [comment]
Ouvi falar que python é usado muito para teste, porém na implementação é mudado pela lentidão do mesmo. Aqui na empresa uma pessoa trabalhou com python e não recomendou, e outra, tendo pouco conhecimento das duas, me disse que ruby tem muito mais praticidade em execução mesmo que python seja um tanto quanto mais fácil de aprender.

**Comment by matheuspoleza** [comment]
@bielcorrea Não sei, cara. A globo.com inteira é feita em Python/Django haha Consigo fazer uma aplicação restful em Python em menos 30 minutos. Todas as aplicações que eu fiz, rodam bem rápido. Estamos falando aqui de Python pra web, para o que ele usou?

**Comment by bielcorrea** [comment]
@matheuspoleza cara, ela me falou que achava lento quando usava para testes gráficos não web. Provável que iremos usar Python mesmo então.

Precisamos apenas dos votos do biel, rob e rodrigo? Quem mais falta?

**Comment by matheuspoleza** [comment]
@bielcorrea só falta do biel e rob

**Comment by rafaelcneves** [comment]
Hoje em dia linguagem não determina muito velocidade, o que determina normalmente é o framework utilizado, mas pelo pouco que sei de django, django e rails são bem similares com relação a velocidade, principalmente porque as duas são altamente escaláveis.. Quando se quer velocidade mesmo você vai pro C.. Alguém quer programar em C? rsrs :yum: 

Uma coisa que reparei, é que bastante gente tem interesse em conhecer ruby. O que acho que pode ser válido é a gente fazer workshops pra galera ir conhecendo, e quem sabe daqui um tempo ir adotando ruby e python de acordo com a necessidade de cada projeto. Eu estou disposto a ajudá-los se for o caso, preparando materiais e talvez até treinamentos.

E sobre app restful em menos de 30 min, sem escopo definido, no rails dá pra fazer com algumas linhas de comando :yum:

**Comment by robsilveirajr** [comment]
Tive um colega de trabalho que desenvolvia em Python, ele falava muito bem da linguagem, eu mesmo achei a organização muito massa (é obrigado a indentar né?) Meu voto vai pro Python, por questões de afinidade.

**Comment by imarinheiro** [comment]
{{ Python Wins. }} (y)

**Comment by matheuspoleza** [comment]
Django/Python ganhou?

**Comment by rafaelcneves** [comment]
Creio que sim.. Agora é só treinar a galera e começar a codar.. :facepunch:

**Comment by matheuspoleza** [comment]
Discussão encerrada. Nova linguagem Python/Django.
